# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               HakShak
tagline:             'Tech Adventures'
description:         'A place to chronicle technolgy combined with my stubbornness.'
baseurl:             http://hakshak.com
paginate:            5

#Since baseurl is changed during development and we don't want to pollute the Disqus admin page, use this.
disqusurl:			 http://hakshak.com

# About/contact
author:
  name:              Nicholas Herring
  url:               https://twitter.com/narkster
  email:             social@hakshak.com
