# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               HakShak
tagline:             'Tech Adventures'
description:         'A place to chronicle technolgy combined with my stubbornness.'
url:                 http://hakshak.com
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Nicholas Herring
  url:               https://twitter.com/narkster
  email:             social@hakshak.com
